"""changed status table

Revision ID: 84cd1809c677
Revises: 6ca5ffa911d8
Create Date: 2023-12-07 23:25:25.894344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cd1809c677'
down_revision: Union[str, None] = '6ca5ffa911d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('max_size_all_text_files', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'max_size_all_text_files')
    # ### end Alembic commands ###
